export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const NEW_POST = 'NEW_POST'
export const LIKE = 'LIKE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const MESSAGES = 'MESSAGES'

