export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const NEW_POST = 'NEW_POST'
export const LIKE = 'LIKE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MESSAGE_ID = 'GET_MESSAGE_ID'
export const GET_LOGOUT = 'GET_LOGOUT'
export const GET_USER = 'GET_USER'
export const SET_ROUTE = 'SET_ROUTE'

